package com.example.demo.mybatis.domain;

import java.util.Date;

public class TrnBooks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trn_books.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trn_books.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trn_books.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trn_books.edition
     *
     * @mbg.generated
     */
    private Integer edition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trn_books.issue_date
     *
     * @mbg.generated
     */
    private Date issue_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trn_books.add_date
     *
     * @mbg.generated
     */
    private Date add_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trn_books.upd_date
     *
     * @mbg.generated
     */
    private Date upd_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trn_books.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trn_books.is_valid
     *
     * @mbg.generated
     */
    private Boolean is_valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trn_books.id
     *
     * @return the value of trn_books.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trn_books.id
     *
     * @param id the value for trn_books.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trn_books.title
     *
     * @return the value of trn_books.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trn_books.title
     *
     * @param title the value for trn_books.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trn_books.author
     *
     * @return the value of trn_books.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trn_books.author
     *
     * @param author the value for trn_books.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trn_books.edition
     *
     * @return the value of trn_books.edition
     *
     * @mbg.generated
     */
    public Integer getEdition() {
        return edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trn_books.edition
     *
     * @param edition the value for trn_books.edition
     *
     * @mbg.generated
     */
    public void setEdition(Integer edition) {
        this.edition = edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trn_books.issue_date
     *
     * @return the value of trn_books.issue_date
     *
     * @mbg.generated
     */
    public Date getIssue_date() {
        return issue_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trn_books.issue_date
     *
     * @param issue_date the value for trn_books.issue_date
     *
     * @mbg.generated
     */
    public void setIssue_date(Date issue_date) {
        this.issue_date = issue_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trn_books.add_date
     *
     * @return the value of trn_books.add_date
     *
     * @mbg.generated
     */
    public Date getAdd_date() {
        return add_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trn_books.add_date
     *
     * @param add_date the value for trn_books.add_date
     *
     * @mbg.generated
     */
    public void setAdd_date(Date add_date) {
        this.add_date = add_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trn_books.upd_date
     *
     * @return the value of trn_books.upd_date
     *
     * @mbg.generated
     */
    public Date getUpd_date() {
        return upd_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trn_books.upd_date
     *
     * @param upd_date the value for trn_books.upd_date
     *
     * @mbg.generated
     */
    public void setUpd_date(Date upd_date) {
        this.upd_date = upd_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trn_books.version
     *
     * @return the value of trn_books.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trn_books.version
     *
     * @param version the value for trn_books.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trn_books.is_valid
     *
     * @return the value of trn_books.is_valid
     *
     * @mbg.generated
     */
    public Boolean getIs_valid() {
        return is_valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trn_books.is_valid
     *
     * @param is_valid the value for trn_books.is_valid
     *
     * @mbg.generated
     */
    public void setIs_valid(Boolean is_valid) {
        this.is_valid = is_valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TrnBooks other = (TrnBooks) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getAuthor() == null ? other.getAuthor() == null : this.getAuthor().equals(other.getAuthor()))
            && (this.getEdition() == null ? other.getEdition() == null : this.getEdition().equals(other.getEdition()))
            && (this.getIssue_date() == null ? other.getIssue_date() == null : this.getIssue_date().equals(other.getIssue_date()))
            && (this.getAdd_date() == null ? other.getAdd_date() == null : this.getAdd_date().equals(other.getAdd_date()))
            && (this.getUpd_date() == null ? other.getUpd_date() == null : this.getUpd_date().equals(other.getUpd_date()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getIs_valid() == null ? other.getIs_valid() == null : this.getIs_valid().equals(other.getIs_valid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getAuthor() == null) ? 0 : getAuthor().hashCode());
        result = prime * result + ((getEdition() == null) ? 0 : getEdition().hashCode());
        result = prime * result + ((getIssue_date() == null) ? 0 : getIssue_date().hashCode());
        result = prime * result + ((getAdd_date() == null) ? 0 : getAdd_date().hashCode());
        result = prime * result + ((getUpd_date() == null) ? 0 : getUpd_date().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getIs_valid() == null) ? 0 : getIs_valid().hashCode());
        return result;
    }
}