package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.domain.TrnBooks;
import com.example.demo.mybatis.domain.TrnBooksExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TrnBooksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    long countByExample(TrnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    int deleteByExample(TrnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    int insert(TrnBooks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    int insertSelective(TrnBooks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    List<TrnBooks> selectByExample(TrnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    TrnBooks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TrnBooks row, @Param("example") TrnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TrnBooks row, @Param("example") TrnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TrnBooks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_books
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TrnBooks row);
}